print('Решение без операторов OR, AND. Работает только с цифрами')
first = input("Введите первое число: ")
first_int = int(first[:])
second = input("Введите второе число: ")
second_int = int(second[:])
third = input("Введите третье число: ")
third_int = int(third[:])
if first_int == second_int == third_int:    print('Количество одинаковых чисел: 3')
elif ((first_int - second_int) * (first_int - third_int) * (second_int - third_int) == 0):
        print('Количество одинаковых чисел: 2')
else: print('Количество одинаковых чисел: 0')

print('Решение c оператором OR. Работает с цифрами и буквами')
first = input("Введите первое число: ")
second = input("Введите второе число: ")
third = input("Введите третье число: ")
if first == second == third:    print('Количество одинаковых чисел: 3')
elif (first == second or first == third or second == third):   print('Количество одинаковых чисел: 2')
else: print('Количество одинаковых чисел: 0')
